# Create a config.yml next to this file to configure this rule
title: Login from an untrusted IP address
trigger:
  - path: $.source
    value: aws.signin
  - path: $.detail.eventName
    value: ConsoleLogin
severity: MEDIUM
trustedIPs:
  - "24.111.111.111"
  - "24.111.111.112"