env:
  browser: false
  commonjs: true
  es6: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  semi: ["error", "always"]
  quotes: ["error", "double"]
  indent: ["error", "tab"]
  no-tabs: 0

