service: cloud-responder
configValidationMode: error
custom:
  defaultRegion: us-east-1

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  memorySize: 128
  versionFunctions: false
  lambdaHashingVersion: 20201221
  region: ${opt:region, self:custom.defaultRegion}
  environment:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/XXXXXXXX/B01H47M6W1E/ofbkuZIVooitaSnZmSmWMcwn

  iam:
   role:
    statements:
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
        # Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:dispatch'
        Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CloudResponderSecret*'
      - Effect: Allow
        Action:
          - sns:Publish
        # Resource: arn:aws:sns:${self:provider.region}:*:dispatch
        Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:dispatch'
      - Effect: Allow
        Action:
          - iam:DeleteUser
          - iam:ListAccessKeys
          - iam:DeleteAccessKey
          - iam:GetLoginProfile
          - iam:GetUser
          - iam:DeleteLoginProfile
        Resource: "*"
      - Effect: Allow
        Action:
          - ec2:DescribeInstanceStatus
          - ec2:DescribeInstances
          - ec2:TerminateInstances
        Resource: "*"

functions:
  authorizer:
    handler: serverless.authorizer
    timeout: 30
  capture:
    handler: serverless.capture
    timeout: 30
    events:
      - http:
          path: capture
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.APIKey

  process:
    handler: serverless.process
    timeout: 900
    events:
      - sns: dispatch

