***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  environment:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/XXXXXXXX/B01H47M6W1E/ofbkuZIVooitaSnZmSmWMcwn

  iam:
   role:
    statements:
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
        # Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:dispatch'
        Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CloudResponderSecret*'
      - Effect: Allow
        Action:
          - sns:Publish
        # Resource: arn:aws:sns:${self:provider.region}:*:dispatch
        Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:dispatch'
      - Effect: Allow
        Action:
          - iam:DeleteUser
          - iam:ListAccessKeys
          - iam:DeleteAccessKey
          - iam:GetLoginProfile
          - iam:GetUser
          - iam:DeleteLoginProfile
        Resource: "*"
      - Effect: Allow
        Action:
          - ec2:DescribeInstanceStatus
          - ec2:DescribeInstances
          - ec2:TerminateInstances
        Resource: "*"

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

