***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  environment:
    EMAIL_TOPIC_ARN: !Ref "EmailTopic"

  iam:
   role:
    statements:
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
        Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CloudResponderSecret*"
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:dispatch"
          - !Ref "EmailTopic"
      - Effect: Allow
        Action:
          - iam:DeleteUser
          - iam:ListAccessKeys
          - iam:DeleteAccessKey
          - iam:GetLoginProfile
          - iam:GetUser
          - iam:DeleteLoginProfile
        Resource: "*"
      - Effect: Allow
        Action:
          - ec2:DescribeInstanceStatus
          - ec2:DescribeInstances
          - ec2:TerminateInstances
        Resource: "*"

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
        ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
  Resources:
    EmailTopic:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
          - Endpoint: "***REMOVED***"
            Protocol: "email"
        TopicName: "EmailTopic"
      # EmailSubscription:
      #   Type: AWS::SNS::Subscription
      #   Properties:
      #     Endpoint: ***REMOVED***
      #     Protocol: email
      #     TopicArn: !Ref 'EmailTopic'