# Create a config.yml next to this file to configure this rule
name: Non compliant user created
trigger:
  - path: $.source
    value: aws.iam
  - path: $.detail.eventName
    value: CreateUser
  - path: $.detail.errorCode
userNamePattern: "[a-z]+_[a-z]+"
severity: HIGH
