# Create a config.yml next to this file to configure this rule
name: Root has logged in
trigger:
  - path: $.source
    value: aws.signin
  - path: $.detail.eventName
    value: ConsoleLogin
  - path: $.detail.userIdentity.type
    value: Root
severity: EXTREME
