# #random channel
webhookURL: "https://hooks.slack.com/services/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"
icons:
  EXTREME: ":bomb:"
  HIGH: ":warning:"
  MEDIUM: ":small_red_triangle:"
  LOW: ":eyes:"